# HW01 - Массивы NymPy

Александрова Мария

В этом задании я создаю массивы NumPy, показываю их форму и тип данных, делаю индексирование, срезы и простые векторные операции.

## Импорт библиотеки
Импортирую библиотеку NumPy и сокращаю имя до np

In [4]:
import numpy as np

## Создание массивов из списков + атрибуты
Создаю одномерный массив из обычного списка Python

In [29]:
mas = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Массив:", mas)

Массив: [10 20 30 40 50 60 70 80]


Создаю двумерный массив (матрицу) из вложенного списка

In [14]:
matrix = np.array([[1.1, 2.2, 3.3],[4.4, 5.5, 6.6]])
print("Матрица: \n", matrix)

Матрица: 
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


Смотрим форму и тип данных для обоих массивов

In [17]:
print("Форма массива mas:", mas.shape)
print("Тип данных mas:", mas.dtype, "\n")

print("Форма массива matrix:", matrix.shape)
print("Тип данных matrix:", matrix.dtype)

Форма массива mas: (4,)
Тип данных mas: int64 

Форма массива matrix: (2, 3)
Тип данных matrix: float64


# zeros / ones / arange
Массив из нулей размера 3×4

In [18]:
zeros_array = np.zeros((3, 4))
print("Массив из нулей 3x4:\n", zeros_array)

Массив из нулей 3x4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Массив из единиц размера 2×2×3

In [19]:
ones_array = np.ones((2, 2, 3))
print("Массив из единиц 2x2x3:\n", ones_array)

Массив из единиц 2x2x3:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


Массив целых чисел от 0 до 9 с шагом 2

In [23]:
range_array = np.arange(0, 10, 2)
print("Получившийся массив", range_array)

Получившийся массив [0 2 4 6 8]


## Индексирование и срезы
Используем уже созданный ранее массив mas

In [30]:
print("Массив:", mas)

Массив: [10 20 30 40 50 60 70 80]


Получаем один элемент по индексу (например, третий элемент)

In [31]:
element = mas[2]  # индексация с нуля
print("Третий элемент mas:", element)

Третий элемент mas: 30


Срез массива: элементы со 2-го по 4-й

In [36]:
subvector = mas[1:4]
print("Срез массива:", subvector)

Срез массива: [20 30 40]


Индексирование матрицы: используем matrix из примера выше

In [37]:
print("Матрица:\n", matrix)

Матрица:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


Элемент второй строки, третьего столбца

In [39]:
elem_matrix = matrix[1, 2]
print("Элемент matrix:", elem_matrix)

Элемент matrix: 6.6


Срез: первая строка целиком

In [40]:
first_row = matrix[0, :]
print("Первая строка матрицы:", first_row)

Первая строка матрицы: [1.1 2.2 3.3]


Срез: первый столбец

In [41]:
first_column = matrix[:, 0]
print("Первый столбец матрицы:", first_column)

Первый столбец матрицы: [1.1 4.4]


## Векторные операции и базовая статистика
Создаём два одинаковых по форме массива для поэлементных операций

In [47]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])
x, y

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

Поэлементное сложение

In [48]:
sum_xy = x + y
print("Поэлементная сумма x + y:", sum_xy)

Поэлементная сумма x + y: [11 22 33 44 55]


Поэлементное умножение

In [49]:
prod_xy = x * y
print("Поэлементное произведение x * y:", prod_xy)

Поэлементное произведение x * y: [ 10  40  90 160 250]


Максимальное значение массива y

In [51]:
max_y = y.max()
print("Максимум y:", max_y)

Максимум y: 50


## Дополнительное

Делаем массив плоским без изменения исходного массива

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

flat = np.ravel(arr)

print("Исходный массив:\n", arr)
print("Плоский массив:\n", flat)

Исходный массив:
 [[1 2 3]
 [4 5 6]]
Плоский массив:
 [1 2 3 4 5 6]


Изменение формы массива

In [56]:
arr2 = np.arange(12)
reshaped = arr2.reshape(3, 4)

print("Исходный массив:", arr2)
print("Массив 3x4:\n", reshaped)

Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Массив 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Работа со случайными числами

In [61]:
# 5 случайных чисел от 0 до 1
arr_rand = np.random.rand(5)
print("5 случайных чисел от 0 до 1:", arr_rand)

# 5 случайных целых чисел от 1 до 9 включительно
arr_int = np.random.randint(1, 10, size=5)
print("5 случайных целых чисел от 1 до 9 включительно:", arr_int)

# Матрица 3x3 со случайными числами
mat = np.random.randn(3, 3)
print("Матрица 3x3 со случайными числами: \n", mat)

5 случайных чисел от 0 до 1: [0.28547959 0.27707013 0.35495781 0.45506314 0.34066524]
5 случайных целых чисел от 1 до 9 включительно: [3 6 8 6 8]
Матрица 3x3 со случайными числами: 
 [[ 0.77937171  0.54402771  0.27049999]
 [ 0.17822699 -1.87042369  2.32892305]
 [-1.85491036  0.68684969 -0.18421995]]


Логические маски и фильтрация элементов

In [66]:
arr3 = np.array([5, 12, 7, 3, 20, 1])

# Смотрим, какое число в массиве больше 10, какое нет
TF = arr3 > 10
print("Маска:", TF)

# Берём только элементы > 10
filtered = arr3[TF]  
print("Отфильтрованный массив:", filtered)

Маска: [False  True False False  True False]
Отфильтрованный массив: [12 20]


## The end...